export const foldersData = [
  {
    id: 1,
    name: 'UI Design',
    type: 'folder',
    date: '05 Feb 2020',
    size: '4 KB',
  },
  {
    id: 2,
    name: 'Ux Design',
    type: 'folder',
    date: '05 Feb 2020',
    size: '4 KB',
  },
  {
    id: 3,
    name: 'UI Pattern.xlsx',
    type: 'xlsx',
    date: '05 Feb 2020',
    size: '4 KB',
  },
  {
    id: 4,
    name: 'UX Research.txt',
    type: 'txt',
    date: '05 Feb 2020',
    size: '4 KB',
  },
];
export const filesData = [
  {
    id: 1,
    name: 'Presentation.xlsx',
    type: 'xlsx',
    date: '05 Feb 2020',
    size: '4 KB',
    starred: true,
  },
  {
    id: 2,
    name: 'UI Kit.Txt',
    type: 'txt',
    date: '05 Feb 2020',
    size: '4 KB',
    starred: false,
  },
  {
    id: 3,
    name: 'UI Design.zip',
    type: 'zip',
    date: '05 Feb 2020',
    size: '4 KB',
    starred: false,
  },
  {
    id: 4,
    name: 'Agile',
    type: 'pdf',
    date: '05 Feb 2020',
    size: '4 KB',
    starred: false,
  },
  {
    id: 5,
    name: 'UI Kit.Txt',
    type: 'txt',
    date: '05 Feb 2020',
    size: '4 KB',
    starred: false,
  },
  {
    id: 6,
    name: 'UI Design.zip',
    type: 'zip',
    date: '05 Feb 2020',
    size: '4 KB',
    starred: false,
  },
];
