export const sections=[
    {
        id:1,
        name:"html",
        lectuers:[
            {
                id:1,
                name:"div",
            },
            {
                id:2,
                name:"image",
            },
            {
                id:3,
                name:"span",
            },
        ]
    },
    {
        id:2,
        name:"css",
        lectuers:[
            {
                id:1,
                name:"color",
            },
            {
                id:2,
                name:"font",
            },
            {
                id:3,
                name:"margin",
            },
        ]
    },
    {
        id:3,
        name:"js",
        lectuers:[
            {
                id:1,
                name:"var",
            },
            {
                id:2,
                name:"let",
            },
            {
                id:3,
                name:"const",
            },
        ]
    },
]