export const allCourses = [
  {
    about:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text\r\n            ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
    assistant_instructors: null,
    category_id: 1,
    certificate_id: null,
    class_id: null,
    complete_order: 0,
    created_at: null,
    dateFormat: '4th Jul, 2022',
    discount_price: 10,
    drip: 0,
    duration: '10',
    enrollCount: 1,
    enrolls: [
      {
        coupon: null,
        course_id: 1,
        created_at: '2022-06-08T12:23:27.000000Z',
        discount_amount: 0,
        enrolledDate: '8th June 2022 18:27 pm',
        id: 1,
        last_view_at: null,
        lms_id: 1,
        purchase_price: 0,
        reason: null,
        reveune: 0,
        status: 1,
        subscription: '0',
        subscription_validity_date: null,
        tracking: 'K3USKPJBC5U8',
        updated_at: '2022-06-08T12:23:27.000000Z',
        user_id: 3,
      },
    ],
    feature: 0,
    host: 'Youtube',
    id: 1,
    image: 'public/frontend/infixlmstheme/img/course/1.jpg',
    lang_id: 19,
    level: 2,
    lms_id: 1,
    meta_description: '',
    meta_keywords: '',
    mode_of_delivery: 1,
    outcomes: '<p>1- 2PHP<br>2- 2Reactjs<br>3- 2MYsqla<br></p>',
    price: 20,
    publish: 1,
    publishedDate: '4th Jul, 2022',
    purchasePrice: 0,
    quiz_id: null,
    required_type: 0,
    requirements: '<p>test 1 <br>test2<br>test3</p>',
    reveiw: 0,
    reveune: 50,
    scope: 1,
    show_mode_of_delivery: 1,
    show_overview_media: 0,
    slug: 'managerial-accounting-advance-course',
    special_commission: null,
    status: 1,
    subcategory_id: 1,
    subscription: '0',
    subscription_list: null,
    sumRev: 0,
    thumbnail: 'public/frontend/infixlmstheme/img/course/1.jpg',
    title: 'Managerial Accounting Advance Course',
    total_enrolled: 1,
    total_rating: 0,
    trailer_link: 'https://www.youtube.com/watch?v=mlqWUqVZrHA',
    type: 1,
    updated_at: '2022-06-22T20:25:42.000000Z',
    user: {
      about:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      access_token: null,
      account_holder_name: null,
      added_by: 0,
      address: null,
      avatar: 'public/demo/user/admin.jpg',
      balance: 0,
      bank_account_number: null,
      bank_name: null,
      bank_type: null,
      blocked_by_me: null,
      branch_name: null,
      city: '15420',
      company_id: null,
      country: '65',
      created_at: '2022-06-09T06:20:02.000000Z',
      currency_id: 6,
      device_token: null,
      dob: null,
      email: 'raed.abdellah@gmail.com',
      email_verified_at: '2022-06-08T18:20:02.000000Z',
      email_verify: '0',
      facebook: '',
      first_name: 'Super admin',
      gender: null,
      headline: 'Administrator',
      id: 1,
      identification_number: null,
      image: 'public/demo/user/admin.jpg',
      instagram: '',
      is_active: 1,
      job_title: null,
      language_code: 'en',
      language_id: '19',
      language_name: 'English',
      language_rtl: 0,
      last_activity_at: '2022-06-22 22:08:09',
      last_name: '',
      linkedin: '',
      lms_id: 1,
      mobile_verified_at: null,
      name: 'Super admin',
      notification_preference: 'mail',
      payout: 'PayPal',
      payout_email: 'demo@paypal.com',
      payout_icon: 'public/uploads/payout/pay_1.png',
      phone: '01841412141',
      photo: 'public/demo/user/admin.jpg',
      policy_id: null,
      provider: null,
      provider_id: null,
      referral: 'p4ukOSjhOO',
      role_id: 1,
      short_details:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      special_commission: 100,
      state: 1048,
      status: 1,
      student_group_id: null,
      student_type: null,
      subscribe: 0,
      subscription_api_key: '',
      subscription_api_status: 0,
      subscription_method: '',
      teach_via: 1,
      total_rating: 0,
      twitter: '',
      updated_at: '2022-06-22T16:08:09.000000Z',
      username: null,
      youtube: null,
      zip: '11012',
      zoom_api_key_of_user: 'tLo47ogGRw-0v9RzbTUVew',
      zoom_api_serect_of_user: 'EAo9SnJmYmewJ4dNSdv4yKptoffqPXndGvY0',
      user_id: 1,
      view: 8,
      what_learn1: null,
      what_learn2: null,
    },
  },
  {
    about:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text\r\n            ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
    assistant_instructors: null,
    category_id: 1,
    certificate_id: null,
    class_id: null,
    complete_order: 0,
    created_at: null,
    dateFormat: '4th Jul, 2022',
    discount_price: 10,
    drip: 0,
    duration: '10',
    enrollCount: 1,
    enrolls: [
      {
        coupon: null,
        course_id: 1,
        created_at: '2022-06-08T12:23:27.000000Z',
        discount_amount: 0,
        enrolledDate: '8th June 2022 18:27 pm',
        id: 1,
        last_view_at: null,
        lms_id: 1,
        purchase_price: 0,
        reason: null,
        reveune: 0,
        status: 1,
        subscription: '0',
        subscription_validity_date: null,
        tracking: 'K3USKPJBC5U8',
        updated_at: '2022-06-08T12:23:27.000000Z',
        user_id: 3,
      },
    ],
    feature: 0,
    host: 'Youtube',
    id: 1,
    image: 'public/frontend/infixlmstheme/img/course/1.jpg',
    lang_id: 19,
    level: 2,
    lms_id: 1,
    meta_description: '',
    meta_keywords: '',
    mode_of_delivery: 1,
    outcomes: '<p>1- 2PHP<br>2- 2Reactjs<br>3- 2MYsqla<br></p>',
    price: 20,
    publish: 1,
    publishedDate: '4th Jul, 2022',
    purchasePrice: 0,
    quiz_id: null,
    required_type: 0,
    requirements: '<p>test 1 <br>test2<br>test3</p>',
    reveiw: 0,
    reveune: 50,
    scope: 1,
    show_mode_of_delivery: 1,
    show_overview_media: 0,
    slug: 'managerial-accounting-advance-course',
    special_commission: null,
    status: 1,
    subcategory_id: 1,
    subscription: '0',
    subscription_list: null,
    sumRev: 0,
    thumbnail: 'public/frontend/infixlmstheme/img/course/1.jpg',
    title: 'Managerial Accounting Advance Course',
    total_enrolled: 1,
    total_rating: 0,
    trailer_link: 'https://www.youtube.com/watch?v=mlqWUqVZrHA',
    type: 1,
    updated_at: '2022-06-22T20:25:42.000000Z',
    user: {
      about:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      access_token: null,
      account_holder_name: null,
      added_by: 0,
      address: null,
      avatar: 'public/demo/user/admin.jpg',
      balance: 0,
      bank_account_number: null,
      bank_name: null,
      bank_type: null,
      blocked_by_me: null,
      branch_name: null,
      city: '15420',
      company_id: null,
      country: '65',
      created_at: '2022-06-09T06:20:02.000000Z',
      currency_id: 6,
      device_token: null,
      dob: null,
      email: 'raed.abdellah@gmail.com',
      email_verified_at: '2022-06-08T18:20:02.000000Z',
      email_verify: '0',
      facebook: '',
      first_name: 'Super admin',
      gender: null,
      headline: 'Administrator',
      id: 2,
      identification_number: null,
      image: 'public/demo/user/admin.jpg',
      instagram: '',
      is_active: 1,
      job_title: null,
      language_code: 'en',
      language_id: '19',
      language_name: 'English',
      language_rtl: 0,
      last_activity_at: '2022-06-22 22:08:09',
      last_name: '',
      linkedin: '',
      lms_id: 1,
      mobile_verified_at: null,
      name: 'Super admin',
      notification_preference: 'mail',
      payout: 'PayPal',
      payout_email: 'demo@paypal.com',
      payout_icon: 'public/uploads/payout/pay_1.png',
      phone: '01841412141',
      photo: 'public/demo/user/admin.jpg',
      policy_id: null,
      provider: null,
      provider_id: null,
      referral: 'p4ukOSjhOO',
      role_id: 1,
      short_details:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      special_commission: 100,
      state: 1048,
      status: 1,
      student_group_id: null,
      student_type: null,
      subscribe: 0,
      subscription_api_key: '',
      subscription_api_status: 0,
      subscription_method: '',
      teach_via: 1,
      total_rating: 0,
      twitter: '',
      updated_at: '2022-06-22T16:08:09.000000Z',
      username: null,
      youtube: null,
      zip: '11012',
      zoom_api_key_of_user: 'tLo47ogGRw-0v9RzbTUVew',
      zoom_api_serect_of_user: 'EAo9SnJmYmewJ4dNSdv4yKptoffqPXndGvY0',
      user_id: 1,
      view: 8,
      what_learn1: null,
      what_learn2: null,
    },
  },
  {
    about:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text\r\n            ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
    assistant_instructors: null,
    category_id: 1,
    certificate_id: null,
    class_id: null,
    complete_order: 0,
    created_at: null,
    dateFormat: '4th Jul, 2022',
    discount_price: 10,
    drip: 0,
    duration: '10',
    enrollCount: 1,
    enrolls: [
      {
        coupon: null,
        course_id: 1,
        created_at: '2022-06-08T12:23:27.000000Z',
        discount_amount: 0,
        enrolledDate: '8th June 2022 18:27 pm',
        id: 1,
        last_view_at: null,
        lms_id: 1,
        purchase_price: 0,
        reason: null,
        reveune: 0,
        status: 1,
        subscription: '0',
        subscription_validity_date: null,
        tracking: 'K3USKPJBC5U8',
        updated_at: '2022-06-08T12:23:27.000000Z',
        user_id: 3,
      },
    ],
    feature: 0,
    host: 'Youtube',
    id: 2,
    image: 'public/frontend/infixlmstheme/img/course/1.jpg',
    lang_id: 19,
    level: 2,
    lms_id: 1,
    meta_description: '',
    meta_keywords: '',
    mode_of_delivery: 1,
    outcomes: '<p>1- 2PHP<br>2- 2Reactjs<br>3- 2MYsqla<br></p>',
    price: 20,
    publish: 1,
    publishedDate: '4th Jul, 2022',
    purchasePrice: 0,
    quiz_id: null,
    required_type: 0,
    requirements: '<p>test 1 <br>test2<br>test3</p>',
    reveiw: 0,
    reveune: 50,
    scope: 1,
    show_mode_of_delivery: 1,
    show_overview_media: 0,
    slug: 'managerial-accounting-advance-course',
    special_commission: null,
    status: 1,
    subcategory_id: 1,
    subscription: '0',
    subscription_list: null,
    sumRev: 0,
    thumbnail: 'public/frontend/infixlmstheme/img/course/1.jpg',
    title: 'Managerial Accounting Advance Course',
    total_enrolled: 1,
    total_rating: 0,
    trailer_link: 'https://www.youtube.com/watch?v=mlqWUqVZrHA',
    type: 1,
    updated_at: '2022-06-22T20:25:42.000000Z',
    user: {
      about:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      access_token: null,
      account_holder_name: null,
      added_by: 0,
      address: null,
      avatar: 'public/demo/user/admin.jpg',
      balance: 0,
      bank_account_number: null,
      bank_name: null,
      bank_type: null,
      blocked_by_me: null,
      branch_name: null,
      city: '15420',
      company_id: null,
      country: '65',
      created_at: '2022-06-09T06:20:02.000000Z',
      currency_id: 6,
      device_token: null,
      dob: null,
      email: 'raed.abdellah@gmail.com',
      email_verified_at: '2022-06-08T18:20:02.000000Z',
      email_verify: '0',
      facebook: '',
      first_name: 'Super admin',
      gender: null,
      headline: 'Administrator',
      id: 3,
      identification_number: null,
      image: 'public/demo/user/admin.jpg',
      instagram: '',
      is_active: 1,
      job_title: null,
      language_code: 'en',
      language_id: '19',
      language_name: 'English',
      language_rtl: 0,
      last_activity_at: '2022-06-22 22:08:09',
      last_name: '',
      linkedin: '',
      lms_id: 1,
      mobile_verified_at: null,
      name: 'Super admin',
      notification_preference: 'mail',
      payout: 'PayPal',
      payout_email: 'demo@paypal.com',
      payout_icon: 'public/uploads/payout/pay_1.png',
      phone: '01841412141',
      photo: 'public/demo/user/admin.jpg',
      policy_id: null,
      provider: null,
      provider_id: null,
      referral: 'p4ukOSjhOO',
      role_id: 1,
      short_details:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      special_commission: 100,
      state: 1048,
      status: 1,
      student_group_id: null,
      student_type: null,
      subscribe: 0,
      subscription_api_key: '',
      subscription_api_status: 0,
      subscription_method: '',
      teach_via: 1,
      total_rating: 0,
      twitter: '',
      updated_at: '2022-06-22T16:08:09.000000Z',
      username: null,
      youtube: null,
      zip: '11012',
      zoom_api_key_of_user: 'tLo47ogGRw-0v9RzbTUVew',
      zoom_api_serect_of_user: 'EAo9SnJmYmewJ4dNSdv4yKptoffqPXndGvY0',
      user_id: 1,
      view: 8,
      what_learn1: null,
      what_learn2: null,
    },
  },
  {
    about:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text\r\n            ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
    assistant_instructors: null,
    category_id: 1,
    certificate_id: null,
    class_id: null,
    complete_order: 0,
    created_at: null,
    dateFormat: '4th Jul, 2022',
    discount_price: 10,
    drip: 0,
    duration: '10',
    enrollCount: 1,
    enrolls: [
      {
        coupon: null,
        course_id: 1,
        created_at: '2022-06-08T12:23:27.000000Z',
        discount_amount: 0,
        enrolledDate: '8th June 2022 18:27 pm',
        id: 1,
        last_view_at: null,
        lms_id: 1,
        purchase_price: 0,
        reason: null,
        reveune: 0,
        status: 1,
        subscription: '0',
        subscription_validity_date: null,
        tracking: 'K3USKPJBC5U8',
        updated_at: '2022-06-08T12:23:27.000000Z',
        user_id: 3,
      },
    ],
    feature: 0,
    host: 'Youtube',
    id: 4,
    image: 'public/frontend/infixlmstheme/img/course/1.jpg',
    lang_id: 19,
    level: 2,
    lms_id: 1,
    meta_description: '',
    meta_keywords: '',
    mode_of_delivery: 1,
    outcomes: '<p>1- 2PHP<br>2- 2Reactjs<br>3- 2MYsqla<br></p>',
    price: 20,
    publish: 1,
    publishedDate: '4th Jul, 2022',
    purchasePrice: 0,
    quiz_id: null,
    required_type: 0,
    requirements: '<p>test 1 <br>test2<br>test3</p>',
    reveiw: 0,
    reveune: 50,
    scope: 1,
    show_mode_of_delivery: 1,
    show_overview_media: 0,
    slug: 'managerial-accounting-advance-course',
    special_commission: null,
    status: 1,
    subcategory_id: 1,
    subscription: '0',
    subscription_list: null,
    sumRev: 0,
    thumbnail: 'public/frontend/infixlmstheme/img/course/1.jpg',
    title: 'Managerial Accounting Advance Course',
    total_enrolled: 1,
    total_rating: 0,
    trailer_link: 'https://www.youtube.com/watch?v=mlqWUqVZrHA',
    type: 1,
    updated_at: '2022-06-22T20:25:42.000000Z',
    user: {
      about:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      access_token: null,
      account_holder_name: null,
      added_by: 0,
      address: null,
      avatar: 'public/demo/user/admin.jpg',
      balance: 0,
      bank_account_number: null,
      bank_name: null,
      bank_type: null,
      blocked_by_me: null,
      branch_name: null,
      city: '15420',
      company_id: null,
      country: '65',
      created_at: '2022-06-09T06:20:02.000000Z',
      currency_id: 6,
      device_token: null,
      dob: null,
      email: 'raed.abdellah@gmail.com',
      email_verified_at: '2022-06-08T18:20:02.000000Z',
      email_verify: '0',
      facebook: '',
      first_name: 'Super admin',
      gender: null,
      headline: 'Administrator',
      id: 4,
      identification_number: null,
      image: 'public/demo/user/admin.jpg',
      instagram: '',
      is_active: 1,
      job_title: null,
      language_code: 'en',
      language_id: '19',
      language_name: 'English',
      language_rtl: 0,
      last_activity_at: '2022-06-22 22:08:09',
      last_name: '',
      linkedin: '',
      lms_id: 1,
      mobile_verified_at: null,
      name: 'Super admin',
      notification_preference: 'mail',
      payout: 'PayPal',
      payout_email: 'demo@paypal.com',
      payout_icon: 'public/uploads/payout/pay_1.png',
      phone: '01841412141',
      photo: 'public/demo/user/admin.jpg',
      policy_id: null,
      provider: null,
      provider_id: null,
      referral: 'p4ukOSjhOO',
      role_id: 1,
      short_details:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      special_commission: 100,
      state: 1048,
      status: 1,
      student_group_id: null,
      student_type: null,
      subscribe: 0,
      subscription_api_key: '',
      subscription_api_status: 0,
      subscription_method: '',
      teach_via: 1,
      total_rating: 0,
      twitter: '',
      updated_at: '2022-06-22T16:08:09.000000Z',
      username: null,
      youtube: null,
      zip: '11012',
      zoom_api_key_of_user: 'tLo47ogGRw-0v9RzbTUVew',
      zoom_api_serect_of_user: 'EAo9SnJmYmewJ4dNSdv4yKptoffqPXndGvY0',
      user_id: 1,
      view: 8,
      what_learn1: null,
      what_learn2: null,
    },
  },
  {
    about:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text\r\n            ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
    assistant_instructors: null,
    category_id: 1,
    certificate_id: null,
    class_id: null,
    complete_order: 0,
    created_at: null,
    dateFormat: '4th Jul, 2022',
    discount_price: 10,
    drip: 0,
    duration: '10',
    enrollCount: 1,
    enrolls: [
      {
        coupon: null,
        course_id: 1,
        created_at: '2022-06-08T12:23:27.000000Z',
        discount_amount: 0,
        enrolledDate: '8th June 2022 18:27 pm',
        id: 1,
        last_view_at: null,
        lms_id: 1,
        purchase_price: 0,
        reason: null,
        reveune: 0,
        status: 1,
        subscription: '0',
        subscription_validity_date: null,
        tracking: 'K3USKPJBC5U8',
        updated_at: '2022-06-08T12:23:27.000000Z',
        user_id: 3,
      },
    ],
    feature: 0,
    host: 'Youtube',
    id: 5,
    image: 'public/frontend/infixlmstheme/img/course/1.jpg',
    lang_id: 19,
    level: 2,
    lms_id: 1,
    meta_description: '',
    meta_keywords: '',
    mode_of_delivery: 1,
    outcomes: '<p>1- 2PHP<br>2- 2Reactjs<br>3- 2MYsqla<br></p>',
    price: 20,
    publish: 1,
    publishedDate: '4th Jul, 2022',
    purchasePrice: 0,
    quiz_id: null,
    required_type: 0,
    requirements: '<p>test 1 <br>test2<br>test3</p>',
    reveiw: 0,
    reveune: 50,
    scope: 1,
    show_mode_of_delivery: 1,
    show_overview_media: 0,
    slug: 'managerial-accounting-advance-course',
    special_commission: null,
    status: 1,
    subcategory_id: 1,
    subscription: '0',
    subscription_list: null,
    sumRev: 0,
    thumbnail: 'public/frontend/infixlmstheme/img/course/1.jpg',
    title: 'Managerial Accounting Advance Course',
    total_enrolled: 1,
    total_rating: 0,
    trailer_link: 'https://www.youtube.com/watch?v=mlqWUqVZrHA',
    type: 1,
    updated_at: '2022-06-22T20:25:42.000000Z',
    user: {
      about:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      access_token: null,
      account_holder_name: null,
      added_by: 0,
      address: null,
      avatar: 'public/demo/user/admin.jpg',
      balance: 0,
      bank_account_number: null,
      bank_name: null,
      bank_type: null,
      blocked_by_me: null,
      branch_name: null,
      city: '15420',
      company_id: null,
      country: '65',
      created_at: '2022-06-09T06:20:02.000000Z',
      currency_id: 6,
      device_token: null,
      dob: null,
      email: 'raed.abdellah@gmail.com',
      email_verified_at: '2022-06-08T18:20:02.000000Z',
      email_verify: '0',
      facebook: '',
      first_name: 'Super admin',
      gender: null,
      headline: 'Administrator',
      id: 5,
      identification_number: null,
      image: 'public/demo/user/admin.jpg',
      instagram: '',
      is_active: 1,
      job_title: null,
      language_code: 'en',
      language_id: '19',
      language_name: 'English',
      language_rtl: 0,
      last_activity_at: '2022-06-22 22:08:09',
      last_name: '',
      linkedin: '',
      lms_id: 1,
      mobile_verified_at: null,
      name: 'Super admin',
      notification_preference: 'mail',
      payout: 'PayPal',
      payout_email: 'demo@paypal.com',
      payout_icon: 'public/uploads/payout/pay_1.png',
      phone: '01841412141',
      photo: 'public/demo/user/admin.jpg',
      policy_id: null,
      provider: null,
      provider_id: null,
      referral: 'p4ukOSjhOO',
      role_id: 1,
      short_details:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      special_commission: 100,
      state: 1048,
      status: 1,
      student_group_id: null,
      student_type: null,
      subscribe: 0,
      subscription_api_key: '',
      subscription_api_status: 0,
      subscription_method: '',
      teach_via: 1,
      total_rating: 0,
      twitter: '',
      updated_at: '2022-06-22T16:08:09.000000Z',
      username: null,
      youtube: null,
      zip: '11012',
      zoom_api_key_of_user: 'tLo47ogGRw-0v9RzbTUVew',
      zoom_api_serect_of_user: 'EAo9SnJmYmewJ4dNSdv4yKptoffqPXndGvY0',
      user_id: 1,
      view: 8,
      what_learn1: null,
      what_learn2: null,
    },
  },
];
