export const queryKeys = {
  cartInfo: 'cart-info',
  webinarInfo: 'webinar-info',
  notifList: 'notif-list',
  wishlist: 'wishlist',
  homeData: 'home-data',
  categoryIndex: 'category-index',
  commentList: 'comment-list',
  commentItem: 'comment-item',
  QAndAList: 'question-and-ask-list',
  announList: 'announcement-list',
  yallaOnlineList: 'yalla-online-list',
  yallaOnlineMeeting: 'yalla-online-meeting',
  yallaOnlineMyGroups: 'yalla-online-my-groups',
  profileStudent: 'profile-student',
  couponList: 'coupon-list',
  courseList: 'course-list',
  coursesEnrolled: 'courses-enrolled',
  yallaOnlineReviewList: 'yalla-online-review-list',
  points: {
    getBalance: 'getBalance',
    getAvailable: 'getAvailable',
  },
};
