import {
  HomeIcon,
  MyCoursesIcon,
  MyProfileIcon,
  YallaOnlineIcon,
  OneToOneIcon,
  CertificateIcon,
  WishlistIcon,
  MeetingSettingsIcon,
  InvoicesIcon,
  QAIcon,
  OneOnOneIcon,
  AnnoncementIcon,
  ReviewsIcon,
  OnGoIcon,
  WebinarsIcon,
  FileManagerIcon,
  ReportsIcon,
  CoursesSideIcon,
  CouponIcon,
} from '../../../../assets/svg';

const dashBoardNavTree = [
  {
    key: 'mydashboard',
    path: `/student-dashboard/mydashboard`,
    title: 'Dashboard',
    icon: HomeIcon,
    breadcrumb: false,
    submenu: [],
    role: 3,
  },
  {
    key: 'myprofile',
    path: `/student-dashboard/my-profile/personal-information`,
    title: 'My Profile',
    icon: MyProfileIcon,
    breadcrumb: false,
    submenu: [],
    role: 3,
  },

  {
    key: 'mycourses',
    path: `/student-dashboard/my-courses`,
    title: 'My Courses',
    icon: MyCoursesIcon,
    breadcrumb: false,
    submenu: [],
    role: 3,
  },
  {
    key: 'yallaonline',
    path: `/student-dashboard/yalla-online`,
    title: 'Yalla online',
    icon: YallaOnlineIcon,
    breadcrumb: false,
    submenu: [],
    role: 3,
  },
  {
    key: 'one-to-one',
    path: `/student-dashboard/one-to-one`,
    title: 'One to one',
    icon: OneToOneIcon,
    breadcrumb: false,
    submenu: [],
    role: 3,
  },
  {
    key: 'certificates',
    path: `/student-dashboard/certificates`,
    title: 'Certificates',
    icon: CertificateIcon,
    breadcrumb: false,
    submenu: [],
    role: 3,
  },
  {
    key: 'my-wishlist',
    path: `/student-dashboard/my-wishlist`,
    title: 'My Wishlist',
    icon: WishlistIcon,
    breadcrumb: false,
    submenu: [],
    role: 3,
  },
  // {
  //   key: 'purchase-history',
  //   path: `/student-dashboard/purchase-history`,
  //   title: 'Purchase History',
  //   icon: PurchaseIcon,
  //   breadcrumb: false,
  //   submenu: [],
  // },
  {
    submenu: [
      {
        key: 'meeting-settings',
        path: `/student-dashboard/meeting-settings`,
        title: 'Meeting Settings',
        icon: MeetingSettingsIcon,
        breadcrumb: true,
        role: 3,
        submenu: [
          {
            key: 'zoom-settings',
            path: `/student-dashboard/zoom-settings`,
            title: 'Zoom Settings',
            icon: null,
            breadcrumb: false,
            submenu: [],
          },
          {
            key: 'bigblue-button-settings',
            path: `/student-dashboard/bigblue-button-settings`,
            title: 'Bigblue Button Settings',
            icon: null,
            breadcrumb: false,
            submenu: [],
          },
          {
            key: 'jitsi-settings',
            path: `/student-dashboard/jitsi-settings`,
            title: 'Jitsi Settings',
            icon: null,
            breadcrumb: false,
            submenu: [],
          },
        ],
      },
    ],
  },
  {
    key: 'invoices',
    path: `/student-dashboard/invoices`,
    title: 'Invoices',
    icon: InvoicesIcon,
    breadcrumb: false,
    submenu: [],
    role: 3,
  },
  {
    key: 'instructor-dashboard',
    path: `/instructor-dashboard/dashboard`,
    title: 'Dashboard',
    icon: HomeIcon,
    breadcrumb: false,
    submenu: [],
    role: 2,
  },
  {
    key: 'myprofile',
    path: `/instructor-dashboard/my-profile/personal-information`,
    title: 'My Profile',
    icon: MyProfileIcon,
    breadcrumb: false,
    submenu: [],
    role: 2,
  },
  {
    key: 'instructor-courses',
    path: `/instructor-dashboard/courses`,
    title: 'Courses',
    icon: CoursesSideIcon,
    breadcrumb: false,
    submenu: [],
    role: 2,
  },
  // {
  //   key: 'َq&a',
  //   path: `/instructor-dashboard/q&a`,
  //   title: 'Q&A',
  //   icon: QAIcon,
  //   breadcrumb: false,
  //   submenu: [],
  //   role: 2,
  // },
  {
    submenu: [
      {
        key: 'one-on-one',
        path: `/instructor-dashboard/one-on-one`,
        title: 'One-on-One',
        icon: OneOnOneIcon,
        breadcrumb: true,
        role: 2,
        submenu: [
          {
            key: 'One-on-one-list',
            path: `/instructor-dashboard/one-on-one-list`,
            title: 'One-on-one list',
            icon: null,
            breadcrumb: false,
            submenu: [],
          },
          // {
          //   key: 'student-request',
          //   path: `/instructor-dashboard/student-request`,
          //   title: 'Student Request',
          //   icon: null,
          //   breadcrumb: false,
          //   submenu: [],
          // },
          {
            key: 'one-on-one-settings',
            path: `/instructor-dashboard/one-on-one-settings`,
            title: 'One-on-one settings',
            icon: null,
            breadcrumb: false,
            submenu: [],
          },
        ],
      },
    ],
  },
  {
    key: 'annoncement',
    path: `/instructor-dashboard/annoncement`,
    title: 'Annoncement',
    icon: AnnoncementIcon,
    breadcrumb: false,
    submenu: [],
    role: 2,
  },
  {
    key: 'reviews',
    path: `/instructor-dashboard/reviews`,
    title: 'Reviews',
    icon: ReviewsIcon,
    breadcrumb: false,
    submenu: [],
    role: 2,
  },
  {
    key: 'on-go',
    path: `/instructor-dashboard/on-go`,
    title: 'On Go',
    icon: OnGoIcon,
    breadcrumb: false,
    submenu: [],
  },
  {
    key: 'webinars-talks',
    path: `/instructor-dashboard/webinars-talks`,
    title: 'Webinars & Talks',
    icon: WebinarsIcon,
    breadcrumb: false,
    submenu: [],
    role: 2,
  },
  {
    key: 'file-manager',
    path: `/instructor-dashboard/file-manager`,
    title: 'File Manager',
    icon: FileManagerIcon,
    breadcrumb: false,
    submenu: [],
    role: 2,
  },
  {
    key: 'reports',
    path: `/instructor-dashboard/reports`,
    title: 'Reports',
    icon: ReportsIcon,
    breadcrumb: false,
    submenu: [],
    role: 2,
  },
  {
    key: 'coupons',
    path: `/instructor-dashboard/coupons`,
    title: 'Coupons',
    icon: CouponIcon,
    breadcrumb: false,
    role: 2,
    submenu: [],

    // submenu: [
    //   {
    //     key: 'coupon-list',
    //     path: `/instructor-dashboard/coupon-list`,
    //     title: 'Coupon List',
    //     icon: null,
    //     breadcrumb: false,
    //     submenu: [],
    //   },
    //   {
    //     key: 'common-coupons',
    //     path: `/instructor-dashboard/common-coupons`,
    //     title: 'Common Coupons',
    //     icon: null,
    //     breadcrumb: false,
    //     submenu: [],
    //   },
    //   {
    //     key: 'single-coupons',
    //     path: `/instructor-dashboard/single-coupons`,
    //     title: 'Single Coupons',
    //     icon: null,
    //     breadcrumb: false,
    //     submenu: [],
    //   },
    //   {
    //     key: 'personalized-coupons',
    //     path: `/instructor-dashboard/personalized-coupons`,
    //     title: 'Personalized Coupons',
    //     icon: null,
    //     breadcrumb: false,
    //     submenu: [],
    //   },
    // ],
  },
  {
    submenu: [
      {
        key: 'meeting-settings',
        path: `/instructor-dashboard/meeting-settings`,
        title: 'Meeting Settings',
        icon: MeetingSettingsIcon,
        breadcrumb: true,
        role: 2,
        submenu: [
          {
            key: 'zoom-settings',
            path: `/instructor-dashboard/zoom-settings`,
            title: 'Zoom Settings',
            icon: null,
            breadcrumb: false,
            submenu: [],
          },
          {
            key: 'bigblue-button-settings',
            path: `/instructor-dashboard/bigblue-button-settings`,
            title: 'Bigblue Button Settings',
            icon: null,
            breadcrumb: false,
            submenu: [],
          },
          {
            key: 'jitsi-settings',
            path: `/instructor-dashboard/jitsi-settings`,
            title: 'Jitsi Settings',
            icon: null,
            breadcrumb: false,
            submenu: [],
          },
        ],
      },
    ],
  },
];

const navigationConfig = [...dashBoardNavTree];

export default navigationConfig;
